# Generated by Django 4.0 on 2022-02-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nimage',
            name='nimage',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='Image'),
        ),
    ]
