# Generated by Django 4.0 on 2022-02-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_nimage_nimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nimage',
            name='nimage',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
