# Generated by Django 4.0 on 2022-02-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_nimage_nimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
