# Generated by Django 4.0 on 2022-02-18 04:03

from django.db import migrations, models
import webpage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=webpage.models.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='NImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimage', models.ImageField(upload_to='', verbose_name='Image')),
            ],
        ),
    ]
