# Generated by Django 4.0 on 2022-02-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='n_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='New_Image'),
        ),
    ]
