# Generated by Django 4.0 on 2022-02-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_image_n_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NImage',
        ),
        migrations.AlterField(
            model_name='image',
            name='n_image',
            field=models.ImageField(default='Default.jpg', upload_to='', verbose_name='New_Image'),
        ),
    ]
